"""Shared default values for user-facing configuration settings."""

# Optimization
DEFAULT_STEPS = 1500
DEFAULT_STYLE_WEIGHT = 1e5
DEFAULT_CONTENT_WEIGHT = 1.0
DEFAULT_OPTIMIZER = "lbfgs"  # Options: "lbfgs", "adam"
DEFAULT_ADAM_LR = 0.03
DEFAULT_LBFGS_LR = 1.0
DEFAULT_INIT_METHOD = "random"
DEFAULT_SEED = 0
DEFAULT_NORMALIZE = True

# Video
DEFAULT_SAVE_EVERY = 20
DEFAULT_FPS = 10
DEFAULT_VIDEO_QUALITY = 10
DEFAULT_CREATE_VIDEO = True
DEFAULT_FINAL_ONLY = False

# Hardware
DEFAULT_DEVICE = "cuda"

# Output
DEFAULT_OUTPUT_DIR = "out"