# Pre-commit hooks for style_transfer_visualizer
# Enforces linting, formatting, and type checking with 2025 best practices

repos:
  # Ruff: Linting, formatting, import sorting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        name: Ruff Linter/Formatter
        args: [--fix]  # auto-fix lint, format, import sort

  # General hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  # Pyrite
  - repo: https://github.com/ComPWA/pyright-pre-commit
    rev: "v1.1.405"
    hooks:
      - id: pyright
