# ============================================================================
# Style Transfer Visualizer Configuration File
#
# This file contains configurable settings for running the style transfer
# visualizer.
#
# Save this file as config.toml and use:
#   python run_visualizer.py --config config.toml
# ============================================================================
[output]
output = "out"

[optimization]
steps = 1500
style_w = 1000000.0
content_w = 1.0
lr = 1.0
# VGG19 layer indices for computing style loss
# Common: [0, 5, 10, 19, 28]
style_layers = [0, 5, 10, 19, 28]
# VGG19 layer indices for computing content loss
# Common: [21]
content_layers = [21]
init_method = "random"
seed = 0
normalize = true

[video]
save_every = 20
fps = 10
quality = 10
create_video = true
final_only = false

[hardware]
device = "cuda"
