# ============================================================================
# Style Transfer Visualizer Configuration File
#
# This file contains configurable settings for running the style transfer
# visualizer.
#
# Save this file as config.toml and use:
#   python run_visualizer.py --config config.toml
# ============================================================================
[output]
output = "out"

[optimization]
steps = 6000
style_w = 10000.0
content_w = 1.0
optimizer = "adam"
lr = 0.001
init_method = "content"
seed = 0
normalize = true

[video]
save_every = 20
fps = 10
quality = 10
create_video = true
final_only = false

[hardware]
device = "cuda"
