
name: Release
description: Track release tasks for a version bump.
title: Release v{{ inputs.version }}
labels:
  - release
  - chore
body:
  - type: input
    id: version
    attributes:
      label: Version number
      description: Provide the version to release (e.g., 1.3.0).
      placeholder: 1.3.0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        This issue tracks the version bump, tagging, and release publishing steps for `v{{ inputs.version }}`.

        ## Tasks

        - [ ] Review all issues completed in milestone `v{{ inputs.version }}`
        - [ ] Create a release branch using this issue
        - [ ] Update `version` in `pyproject.toml` to `{{ inputs.version }}`
        - [ ] Add release notes to RELEASES.md
        - [ ] Commit with:
          ```sh
          git commit -m "chore: bump version to {{ inputs.version }}"
          ```
        - [ ] Push and open PR titled:
          ```
          chore: release v{{ inputs.version }}
          ```
        - [ ] Squash and merge PR
        - [ ] Tag the release:
          ```sh
          git tag v{{ inputs.version }}
          git push origin v{{ inputs.version }}
          ```
        - [ ] Create GitHub Release with:
          - Title: `v{{ inputs.version }}`
          - Description: Closed issues, changelog, or summary

        ## Notes
        - Link this issue to the release PR using `Closes #XXX` or mention it manually.
        - Delete the release branch after merging.
